services:
  tg-bot:
    build: .
    container_name: ya_mark_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./lang.yaml:/app/lang.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]